theme: sparkles
title: Software engineering blog
author: Vivekananda Reddy Ponugoti
description: Blog post to update my new learning in software engineering and pragmatics of learning new programming languages
